Repository betagouv/ma-cantine, pull requests merged in 2023-10, with the labels that each got.

#3094 Reparer bug pour les satellites sans CC dans notre BDD
  frontend/src/views/DashboardManager/ApproSegment.vue
  frontend/src/views/DashboardManager/DiversificationCard.vue
  frontend/src/views/DashboardManager/FoodWasteCard.vue
  frontend/src/views/DashboardManager/InformationCard.vue
  frontend/src/views/DashboardManager/NoPlasticCard.vue
Labels: dashboard

#3081 Affichage de « année en cours » pour le segment du dashboard pour l'année en cours
  frontend/src/components/DsfrBadge.vue
  frontend/src/views/DashboardManager/DataInfoBadge.vue
  frontend/src/views/DashboardManager/DiversificationCard.vue
  frontend/src/views/DashboardManager/EgalimProgression.vue
  frontend/src/views/DashboardManager/FoodWasteCard.vue
  frontend/src/views/DashboardManager/InformationCard.vue
  frontend/src/views/DashboardManager/MissingDataChip.vue
  frontend/src/views/DashboardManager/NoPlasticCard.vue
Labels: dashboard

#3096 Ma progression - enchaufage et info gaspi
  frontend/src/views/MyProgress/ProgressTab.vue
  frontend/src/views/MyProgress/index.vue
  frontend/src/views/MyProgress/information/DiversificationMeasureInfo.vue
  frontend/src/views/MyProgress/information/InformationMeasureInfo.vue
  frontend/src/views/MyProgress/information/NoPlasticMeasureInfo.vue
  frontend/src/views/MyProgress/information/QualityMeasureInfo.vue
  frontend/src/views/MyProgress/information/WasteMeasureInfo.vue
  frontend/src/views/MyProgress/summary/CanteenSummary.vue
  frontend/src/views/MyProgress/summary/DiversificationMeasureSummary.vue
  frontend/src/views/MyProgress/summary/InformationMeasureSummary.vue
  frontend/src/views/MyProgress/summary/NoPlasticMeasureSummary.vue
  frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
  frontend/src/views/MyProgress/summary/WasteMeasureSummary.vue
Labels: ma progression

#3103 Introduction pour la mesure info convives
  frontend/src/views/MyProgress/information/InformationMeasureInfo.vue
Labels: ma progression

#3102 Info plastiques
  frontend/src/views/MyProgress/information/NoPlasticMeasureInfo.vue
Labels: ma progression

#3109 Fix du bug ne permettant pas de modifier la participation aux XP
  frontend/src/components/KeyMeasureDiagnostic/DiversificationMeasure.vue
  frontend/src/components/KeyMeasureDiagnostic/WasteMeasure.vue
  frontend/src/views/DiagnosticEditor/index.vue
Labels: 🚨 bug prod

#3101 Info diversification
  frontend/src/views/MyProgress/information/DiversificationMeasureInfo.vue
Labels: ma progression

#3100 Introduction mesure appro
  frontend/src/components/CanteenDashboard.vue
  frontend/src/views/MyProgress/ProgressTab.vue
  frontend/src/views/MyProgress/information/QualityMeasureInfo.vue
Labels: ma progression
