Repository betagouv/ma-cantine, pull requests merged in 2024-03, with the labels that each got.

#3681 Améliorer texte du lien dans l'en-tête
  frontend/src/components/AppHeader.vue
Labels: a11y, Lien

#3706 :bug: Permet d'importer des fichier sans `local_definition`
  api/tests/files/good_purchase_import_no_local_def.csv
  api/tests/test_import_purchases.py
  api/views/purchaseimport.py
Labels: 🚨 bug prod

#3709 Bug fix : enlever le bon satellite
  frontend/src/components/SatelliteTable.vue
Labels: 🚨 bug prod

#3685 RGAA 11.1 Chaque champ de formulaire a-t-il une étiquette ?
  frontend/src/components/DsfrSearchField.vue
  frontend/src/views/CanteenEditor/CanteenForm.vue
Labels: a11y, Formulaire

#3679 RGAA 1.1 s'assurer que les icônes pertinates ont de texte alternatif
  frontend/src/components/AppFooter.vue
  frontend/src/components/AppHeader.vue
  frontend/src/components/CanteenDashboard.vue
  frontend/src/components/DiagnosticSummary/InformationMeasureSummary.vue
  frontend/src/components/ImageGallery.vue
  frontend/src/components/KeyMeasureDiagnostic/ExpeModals/ExpeVegetarian.vue
  frontend/src/components/KeyMeasureResource/QualityMeasure.vue
  frontend/src/components/PartnerIndicators.vue
  frontend/src/components/PurchasesTable.vue
  frontend/src/components/SatelliteTable.vue
  frontend/src/views/AccessibilityDeclaration.vue
  frontend/src/views/CanteenEditor/CanteenForm.vue
  frontend/src/views/CanteenEditor/PublicationForm/index.vue
  frontend/src/views/CanteenEditor/SatelliteManagement/AddSatellite.vue
  frontend/src/views/CanteensPage/CanteenWidget.vue
  frontend/src/views/CanteensPage/ContactForm.vue
  frontend/src/views/CommunityPage/FacebookSection.vue
  frontend/src/views/ContactPage.vue
  frontend/src/views/DashboardManager/TeamWidget.vue
  frontend/src/views/DeveloperPage.vue
  frontend/src/views/DiagnosticPage.vue
  frontend/src/views/DiagnosticTunnel/WasteMeasureSteps/index.vue
  frontend/src/views/DiagnosticTunnel/index.vue
  frontend/src/views/FaqPage/AnswerComponents/NoSiret.vue
  frontend/src/views/FaqPage/AnswerComponents/ProviderObligation.vue
  frontend/src/views/FaqPage/AnswerComponents/SiretRequired.vue
  frontend/src/views/LandingPage/Resources.vue
  frontend/src/views/ManagementPage/TeledeclarationBanner.vue
  frontend/src/views/ManagementPage/UserTools.vue
  frontend/src/views/ManagementPage/index.vue
  frontend/src/views/NewPartner.vue
  frontend/src/views/PrivacyPolicy/index.vue
  frontend/src/views/PublicCanteenStatisticsPage/BadgesExplanation.vue
  frontend/src/views/PurchasesHome.vue
Labels: a11y, Image

#3698 RGAA 10.8 Pour chaque page web, les contenus cachés ont-ils vocation à être ignorés par les technologies d’assistance ?
  frontend/src/components/CanteenPublication.vue
  frontend/src/components/DsfrAccordion.vue
  frontend/src/components/MultiYearSummaryStatistics.vue
  frontend/src/utils.js
Labels: a11y

#3728 RGAA 12.3 La page « plan du site » est-elle pertinente ?
  frontend/src/router/index.js
  frontend/src/views/SiteMap.vue
Labels: a11y

#3699 Refactoriser pour utiliser nouveau composant DSFR accordéon
  frontend/src/components/DiagnosticSummary/QualityMeasureSummary.vue
  frontend/src/components/DsfrAccordion.vue
  frontend/src/components/MultiYearSummaryStatistics.vue
  frontend/src/views/FaqPage/FaqPanels.vue
  frontend/src/views/PublicCanteenStatisticsPage/BadgesExplanation.vue
Labels: UI-UX

#3740 RGAA 9.1 et 9.3 descriptions des mesures
  frontend/src/components/KeyMeasureDescription.vue
  frontend/src/components/KeyMeasureDescriptionLabels.vue
  frontend/src/data/key-measures.json
Labels: a11y
