Repository betagouv/ma-cantine, pull requests merged in 2024-09, with the labels that each got.

#4271 Docs : comment faire une mise en prod
  docs/ONBOARDING.md
Labels: documentation

#4372 CMS : Actions anti-gaspi : améliorer la navigation dans Wagtail
  cms/filtersets/wasteaction.py
  cms/viewsets/wasteaction.py
Labels: CMS, actions anti-gaspi

#4434 Lancer pre-commit sur tous les fichiers sur staging, en corrigant quelques pbs
  .pre-commit-config.yaml
  api/tests/files/diagnostics_decimal_number.csv
  api/tests/files/purchase_import_delimiter_tab.tsv
  api/tests/test_import_purchases.py
  cms/admin.py
  cms/models.py
  cms/models/__init__.py
  cms/views.py
  data/apps.py
  data/schemas/README.md
  data/schemas/param_non_retenus_cantines.json
  data/schemas/param_non_retenus_td.json
  macantine/management/commands/importcsv.py
  scripts/field_gen.py
  web/static/css/easy-autocomplete.min.css
  web/static/js/jquery.easy-autocomplete.min.js
  web/templates/googlefbd6f06a151f47ee.html
Labels: tech debt

#4487 Bug fix, actions anti-gaspi : MAJ la vue liste quand on change de page
  frontend/src/views/WasteActionsPage/WasteActionsListView.vue
Labels: Bug staging
