Repository betagouv/ma-cantine, pull requests merged in 2024-04, with the labels that each got.

#3765 RGAA 7.4 Pour chaque script qui initie un changement de contexte, l’utilisateur est-il averti ou en a-t-il le contrôle ?
  frontend/src/views/CanteensPage/CanteensHome.vue
Labels: a11y, Script

#3763 RGAA 10.11 Pour chaque page web, les contenus peuvent-ils être présentés sans perte d’information ou de fonctionnalité et sans avoir recours soit à un défilement vertical pour une fenêtre ayant une hauteur de 256 px, soit à un défilement horizontal pour une fenêtre ayant une largeur de 320 px (hors cas particuliers) ?
  frontend/src/data/key-measures.json
  frontend/src/views/CanteensPage/ContactForm.vue
  frontend/src/views/DashboardManager/CanteenInfoWidget.vue
  frontend/src/views/DashboardManager/EgalimProgression.vue
  frontend/src/views/DashboardManager/PublicationWidget.vue
  frontend/src/views/DashboardManager/PurchasesWidget.vue
  frontend/src/views/DashboardManager/SatellitesWidget.vue
  frontend/src/views/DashboardManager/TeamWidget.vue
  frontend/src/views/DiagnosticPage.vue
  frontend/src/views/LegalNotices.vue
  frontend/src/views/ManagementPage/TeledeclarationBanner.vue
  frontend/src/views/MyProgress/index.vue
  frontend/src/views/PublicCanteenStatisticsPage/index.vue
Labels: a11y, Présentation

#3760 RGAA 3.2 Dans chaque page web, le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ?
  frontend/src/App.vue
  frontend/src/components/DiagnosticSummary/QualityMeasureSummary.vue
  frontend/src/components/KeyMeasureScore.vue
  frontend/src/components/NotificationSnackbar.vue
  frontend/src/views/CanteensPage/CanteensHome.vue
  frontend/src/views/DashboardManager/SatellitesWidget.vue
  frontend/src/views/DiagnosticPage.vue
  frontend/src/views/PendingActions/AnnualActionableCanteensTable.vue
  frontend/src/views/PurchasesHome.vue
Labels: a11y, Couleur

#3837 Ne pas utiliser l API geo pour le jeu de donnes registre cantines
  macantine/extract_open_data.py
  macantine/tests/test_extract_open_data.py
Labels: 🚨 bug prod

#3847 Mobile : reparer overflow bouton
  frontend/src/views/DashboardManager/EgalimProgression.vue
Labels: 🚨 bug prod, UI-UX
